import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './redux/provider'
import { Suspense } from 'react'
import Loading from './posts/[id]/loading'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white text-black'>
        
        <div className=' bg-gray-900'>
          <div className='container mx-auto py-3 text-2xl font-extrabold text-white'>
            <Link href={"/"}>
            <h1>
            MAGFİ
            </h1>
            </Link>
            </div>
        </div>
  
        <Providers>{children}</Providers>
  
        </body>
    </html>
  )
}
